---
- block:
    - name: install required packages
      package:
        name:
          - apt-transport-https
        state: present

    - name: download GPG signing keys
      get_url:
        url: '{{ item.value }}'
        dest: /etc/apt/trusted.gpg.d/{{ item.key }}
      with_dict:
        knot.gpg: https://packages.sury.org/knot/apt.gpg
        knot-resolver.gpg: https://packages.sury.org/knot-resolver/apt.gpg

    - name: add knot/knot-resolver repos
      copy:
        content: |
          deb https://deb.knot-dns.cz/{{ item }}/ {{ ansible_distribution_release }}  main
        dest: /etc/apt/sources.list.d/{{ item }}.list
      with_items:
        - knot
        - knot-resolver

    - name: apt-get update
      shell: apt-get update
  when: ansible_distribution == 'Debian'
