# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.network "private_network", ip: "192.168.231.11"

    config.vm.synced_folder "./", "/vagrant",
        type: "nfs",
        nfs_udp: false

    config.vm.synced_folder "/home/tkrizek/git", "/mnt/git",
        type: "nfs",
        nfs_udp: false

    config.vm.synced_folder "/home/tkrizek/pkg", "/mnt/pkg",
        type: "nfs",
        nfs_udp: false

    config.vm.box = "fedora/29-cloud-base"
#    config.vm.box_version = ""

    config.vm.provider "virtualbox" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

    config.vm.define "f29-pkg_vm"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/default.yaml"
            ansible.extra_vars = {
                packager: true
            }
        end
    end

end
