---
# - block:
#     - name: permanently turn off selinux
#       selinux:
#         policy: targeted
#         state: permissive
#     - name: temporarily turn off selinux
#       shell: setenforce 0
#   when: ansible_os_family == 'RedHat'

- name: make vim behave as terminal
  lineinfile:
    create: true
    line: set mouse=""
    path: '{{ item }}'
    state: present
  with_items:
    - /root/.vimrc
    - ~/.vimrc

- name: set up package mirrors
  copy:
    content: |
      ## Arch Linux repository mirrorlist
      ## Generated on 2018-11-26
      ## Czechia
      Server = http://mirrors.nic.cz/archlinux/$repo/os/$arch
      Server = http://ftp.fi.muni.cz/pub/linux/arch/$repo/os/$arch
      Server = http://ftp.sh.cvut.cz/arch/$repo/os/$arch
      Server = http://gluttony.sin.cvut.cz/arch/$repo/os/$arch
    dest: /etc/pacman.d/mirrorlist
  when: ansible_distribution_file_variety == 'Archlinux'

- name: install nfs-utils on EL8+
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: install epel-release
  dnf:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: enable AlmaLinux repositories
  ansible.builtin.replace:
    path: /etc/yum.repos.d/almalinux-crb.repo
    regexp: enabled=0
    replace: enabled=1
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 9
