# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

#    config.ssh.username = "root"

    config.vm.synced_folder "/home/tkrizek/pkg", "/mnt/pkg",
        type: "nfs",
        nfs_udp: false

    config.vm.box = "fedora/27-cloud-base"
#    config.vm.box_version = ""

    config.vm.provider "libvirt" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

    config.vm.define "vm"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/knot-resolver-test.yaml"
            ansible.extra_vars = {
                test_update: false,
                rpm: 'knot-resolver-*.fc27.x86_64.rpm',
                hostname: 'fedora-27-kresd-install',
            }
        end
    end

end
