# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "generic/rocky8"

    config.vm.define "vm_rocky-8"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/default.yaml"
            ansible.extra_vars = {
            }
        end
    end

    config.vm.synced_folder "./", "/vagrant",
        type: "nfs"
    config.vm.synced_folder "/home/tkrizek/git", "/mnt/git",
        type: "nfs"

    config.vm.provider "libvirt" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

end
