# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "debian/stretch64"

    config.vm.define "vm_stretch"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/default.yaml"
            ansible.extra_vars = {
                # knot_resolver_repos: true,
                obs_repos: ['knot-resolver-testing', 'knot-resolver-latest'],
            }
        end
    end

    config.vm.synced_folder "./", "/vagrant",
        type: "nfs",
        nfs_version: 3,
        nfs_udp: false

    config.vm.synced_folder "/home/tkrizek/git", "/mnt/git",
        type: "nfs",
        nfs_version: 3,
        nfs_udp: false

    config.vm.synced_folder "/home/tkrizek/pkg", "/mnt/pkg",
        type: "nfs",
        nfs_version: 3,
        nfs_udp: false

    config.vm.provider "libvirt" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

end
