---
- name: install epel
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: configure OBS repository
  shell: "{{ configure_obs_repo[ansible_distribution] }}"
  args:
    warn: false
  with_items: "{{ obs_repos }}"
  when: ansible_distribution != 'Archlinux'

- block:
    - name: configure OBS repository (Arch)
      blockinfile:
        block: |
          [home_CZ-NIC_{{ item }}_Arch]
          SigLevel = Never
          Server = https://download.opensuse.org/repositories/home:/CZ-NIC:/{{ item }}/Arch/$arch
        insertbefore: '^\[core\]'
        path: /etc/pacman.conf
        state: present
      with_items: "{{ obs_repos }}"
    - name: sync repos (Arch)
      shell: pacman -Syu --noconfirm
  when: ansible_distribution == 'Archlinux'
