---
- hosts: all

  remote_user: root
  become: true

  vars:  # defaults
    packager: false
    knot_resolver_repos: true

  roles:
    - rxvt-unicode
    - packages
    - configuration
    - role: knot-resolver-repos
      when: knot_resolver_repos
    - role: packager
      when: packager

  # HACK: Ansible requires Python 2, but it's not installed by default in all distros
  gather_facts: false
  pre_tasks:
    - name: install python and deps for ansible modules
      raw: |
        yum install -y python2 python2-dnf libselinux-python || \
        pacman -Sy python2 --noconfirm || \
        (zypper --gpg-auto-import-keys refresh && zypper install -y python) || \
        (apt-get update && apt-get install -y python) || \
        :
      ignore_errors: true
    - name: gather facts
      setup:
