---
- hosts: all

  remote_user: root
  become: true

  vars:  # defaults
    packager: false
    knot_resolver_repos: true

  roles:
    - rxvt-unicode
    - packages
    - configuration
    - role: knot-resolver-repos
      when: knot_resolver_repos
    - role: packager
      when: packager

  # HACK: Ansible requires Python 2, but it's not installed by default in Fedora
  gather_facts: false
  pre_tasks:
    - block:
        - name: install ansible deps (redhat)
          raw: "yum install -y python2 python2-dnf libselinux-python ||:"
        - name: install ansible deps (arch)
          raw: "pacman -Sy python2 --noconfirm ||:"
        - name: install ansible (debian, opensuse)
          raw: "apt-get install -y python ||:"
    - name: gather facts
      setup:
