---
- hosts: all

  remote_user: root
  become: true

  vars:  # defaults
    packager: false

  roles:
    - rxvt-unicode
    - packages
    - knot
    - configuration
    - role: packager
      when: packager

  # HACK: Ansible requires Python 2, but it's not installed by default in Fedora
  gather_facts: false
  pre_tasks:
    - block:
        - name: install python and deps for ansible modules (redhat)
          raw: yum install -y python2 python2-dnf libselinux-python
      rescue:
        - block:  # arch
            - name: install python2 (arch)
              raw: pacman -Sy python2 --noconfirm
          rescue:
            - name: install python2 (debian)
              raw: apt-get install -y python
    - name: gather facts
      setup:
