# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    #config.ssh.username = "root"

    config.vm.synced_folder "./", "/vagrant",
        type: "rsync"
#        type: "nfs",
#        nfs_udp: false

    config.vm.box = "opensuse/openSUSE-Tumbleweed-x86_64"
#    config.vm.box_version = ""

    config.vm.provider "libvirt" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

    config.vm.define "vm"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/default.yaml"
        end
    end

end
