# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "generic/fedora30"

    config.vm.define "vm_f30"  do |vm|
        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "../provision/default.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
                # packager: true
            }
        end
    end

    # config.vm.synced_folder "./", "/vagrant",
    #     type: "nfs"
    # config.vm.synced_folder "/home/tkrizek/git", "/mnt/git",
    #     type: "nfs"
    # config.vm.synced_folder "/home/tkrizek/pkg", "/mnt/pkg",
    #     type: "nfs"

    config.vm.provider :libvirt do |v, override|
        v.disk_bus = "sata"
    end

    config.vm.provider "libvirt" do |domain, override|
        domain.cpus = 1
        domain.memory = 2048
    end

end
